### ISSUE TITLE
request for update

### ISSUE THREAD

**Issue by GitMensch** [jpakkane/arducob#1]
It would be nice to update README.md (the Meson branch is merged now, for example) and give more detailed explanation what version of GnuCOBOL you've used and how you actually run `cobc` (is this done on a different machine?) and why you can't use the "real" libcob (maybe in a minimized version).

**Comment by jpakkane** [comment]
Updated, thanks. The build logic is all inside the Meson definitions. Simply following the build instructions takes care of invoking the compiler.

**Comment by GitMensch** [comment]
Where did you update? I can't find the actual build instructions.
I *assume* this works the way:

* install GnuCOBOL on your development machine
* somehow invoke Meson build to cross-compile gnucobol for Arduno
* somehow invoke Meson build to use cobc to compile the COBOL modules for Arduno
* copy everything to the Arduno

But I don't think it actually works this way.

**Comment by jpakkane** [comment]
I botched up the push. It should be fixed now.

The build does not cross compile GNU Cobol at all. It just invokes the existing compiler with -C to generate a C source file corresponding to the .cob file. It then compiles this source + a hand written file which has stub implementations for those functions that are needed to run the program.

It is a hack done for fun, not really something ready for actual production use.

**Comment by GitMensch** [comment]
> It is a hack done for fun, not really something ready for actual production use.

What do you think about changing the Meson build path to take arguments (the current `cobc` invocation and the name of the source file [there can currently be only one in the script] are hard-coded) and maybe extend your minimal libcob or even better: hack the "real" libcob to allow a stripped-down version that can be used on the Arduino (with a minimal subset of the cobol runtime)?

**Comment by jpakkane** [comment]
All of this is doable in theory.

 - Meson has support for processing many Cobol source files instead of one, it's just a question of users adding their sources to the build definition
 - If libcob can be cross compiled _and_ it is small enough to fit on an Arduino _and_ it can be compiled without needing libc (because Arduino does not have one) _and_ it works on an 8-bit processor then it could be made to work

This is not something that I intend to do because I have enough crazy projects on my plate already. However if someone else wants to do it, go for it.
